version: '3'
services:
  app:
    build:
      context: target
      dockerfile: Dockerfile
    ports:
      - "8034:8034"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/trainDDBB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mypassword
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: trainDDBB
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
volumes:
  db_data:
